# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conf_admitancia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Conf_admitancia(object):
    def setupUi(self, Conf_admitancia):
        Conf_admitancia.setObjectName("Conf_admitancia")
        Conf_admitancia.resize(326, 251)
        self.constante_c = QtWidgets.QDoubleSpinBox(Conf_admitancia)
        self.constante_c.setGeometry(QtCore.QRect(240, 16, 69, 26))
        self.constante_c.setWrapping(False)
        self.constante_c.setReadOnly(False)
        self.constante_c.setAccelerated(True)
        self.constante_c.setPrefix("")
        self.constante_c.setDecimals(3)
        self.constante_c.setMinimum(0.0)
        self.constante_c.setMaximum(1.0)
        self.constante_c.setSingleStep(0.01)
        self.constante_c.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.constante_c.setObjectName("constante_c")
        self.umbral_fx = QtWidgets.QDoubleSpinBox(Conf_admitancia)
        self.umbral_fx.setGeometry(QtCore.QRect(240, 56, 69, 26))
        self.umbral_fx.setDecimals(0)
        self.umbral_fx.setMaximum(1000.0)
        self.umbral_fx.setSingleStep(1.0)
        self.umbral_fx.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.umbral_fx.setObjectName("umbral_fx")
        self.umbral_fy = QtWidgets.QDoubleSpinBox(Conf_admitancia)
        self.umbral_fy.setGeometry(QtCore.QRect(240, 96, 69, 26))
        self.umbral_fy.setDecimals(0)
        self.umbral_fy.setMaximum(1000.0)
        self.umbral_fy.setSingleStep(1.0)
        self.umbral_fy.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.umbral_fy.setObjectName("umbral_fy")
        self.umbral_fz = QtWidgets.QDoubleSpinBox(Conf_admitancia)
        self.umbral_fz.setGeometry(QtCore.QRect(240, 136, 69, 26))
        self.umbral_fz.setDecimals(0)
        self.umbral_fz.setMaximum(1000.0)
        self.umbral_fz.setSingleStep(1.0)
        self.umbral_fz.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.umbral_fz.setObjectName("umbral_fz")
        self.label = QtWidgets.QLabel(Conf_admitancia)
        self.label.setGeometry(QtCore.QRect(20, 20, 201, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Conf_admitancia)
        self.label_2.setGeometry(QtCore.QRect(20, 61, 201, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Conf_admitancia)
        self.label_3.setGeometry(QtCore.QRect(20, 101, 201, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Conf_admitancia)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 201, 17))
        self.label_4.setObjectName("label_4")
        self.aceptar = QtWidgets.QDialogButtonBox(Conf_admitancia)
        self.aceptar.setGeometry(QtCore.QRect(138, 215, 175, 25))
        self.aceptar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptar.setObjectName("aceptar")
        self.lim_velocidad = QtWidgets.QDoubleSpinBox(Conf_admitancia)
        self.lim_velocidad.setGeometry(QtCore.QRect(240, 176, 69, 26))
        self.lim_velocidad.setDecimals(1)
        self.lim_velocidad.setMaximum(100.0)
        self.lim_velocidad.setSingleStep(1.0)
        self.lim_velocidad.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.lim_velocidad.setObjectName("lim_velocidad")
        self.label_5 = QtWidgets.QLabel(Conf_admitancia)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 201, 17))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Conf_admitancia)
        QtCore.QMetaObject.connectSlotsByName(Conf_admitancia)

    def retranslateUi(self, Conf_admitancia):
        _translate = QtCore.QCoreApplication.translate
        Conf_admitancia.setWindowTitle(_translate("Conf_admitancia", "Configurar control de admitancia"))
        self.label.setText(_translate("Conf_admitancia", "Constante de amortiguación:"))
        self.label_2.setText(_translate("Conf_admitancia", "Umbral de fuerza X(N):"))
        self.label_3.setText(_translate("Conf_admitancia", "Umbral de fuerza Y(N):"))
        self.label_4.setText(_translate("Conf_admitancia", "Umbral de fuerza Z(N):"))
        self.label_5.setText(_translate("Conf_admitancia", "Límite de velocidad (m/s):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Conf_admitancia = QtWidgets.QDialog()
    ui = Ui_Conf_admitancia()
    ui.setupUi(Conf_admitancia)
    Conf_admitancia.show()
    sys.exit(app.exec_())
