# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_control(object):
    def setupUi(self, MainWindow_control):
        MainWindow_control.setObjectName("MainWindow_control")
        MainWindow_control.setEnabled(True)
        MainWindow_control.resize(790, 733)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_control.sizePolicy().hasHeightForWidth())
        MainWindow_control.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow_control.setPalette(palette)
        MainWindow_control.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow_control)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 2361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 235, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 107, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 215, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(182, 235, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 235, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 107, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 215, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(182, 235, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 107, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 235, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 107, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 107, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 107, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 215, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 215, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 215, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setStyleSheet("QWidget#tab{\n"
"    background-color: qradialgradient(spread:pad, cx:0.295522, cy:0.590909, radius:2, fx:0.445716, fy:0.392409, stop:0 rgba(255, 255, 255, 255), stop:0.955224 rgba(158, 158, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"\n"
"}\n"
"\n"
"QWidget#tab_2{\n"
"    background-color: qradialgradient(spread:pad, cx:0.295522, cy:0.590909, radius:2, fx:0.445716, fy:0.392409, stop:0 rgba(255, 255, 255, 255), stop:0.930348 rgba(10, 10, 10, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"    background-color: qradialgradient(spread:pad, cx:0.295522, cy:0.590909, radius:2, fx:0.445716, fy:0.392409, stop:0 rgba(255, 255, 255, 255), stop:0.955224 rgba(158, 158, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}\n"
"QPushButton#q1_derecha{\n"
"background-color: rgb(150, 255, 253);\n"
"    border-color: rgb(255, 255, 255);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q1_derecha:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"    border-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton#q1_derecha:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"    border-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton#q2_derecha{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q2_derecha:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q2_derecha:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q3_derecha{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q3_derecha:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q3_derecha:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q4_derecha{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q4_derecha:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q4_derecha:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q5_derecha{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q5_derecha:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q5_derecha:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q6_derecha{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q6_derecha:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q6_derecha:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q1_izquierda{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q1_izquierda:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q1_izquierda:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q2_izquierda{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q2_izquierda:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q2_izquierda:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q3_izquierda{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q3_izquierda:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q3_izquierda:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q4_izquierda{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q4_izquierda:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q4_izquierda:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q5_izquierda{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q5_izquierda:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q5_izquierda:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#q6_izquierda{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#q6_izquierda:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#q6_izquierda:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"QPushButton#home{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#home:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#home:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"QPushButton#repeticiones{\n"
"background-color: rgb(110, 215, 213);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#repeticiones:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#repeticiones:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#duracion{\n"
"background-color: rgb(110, 215, 213);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#duracion:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#duracion:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"QPushButton#visualizar_ejercicio{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#visualizar_ejercicio:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#visualizar_ejercicio:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"QPushButton#ejecutar_ejercicio{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#ejecutar_ejercicio:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#ejecutar_ejercicio:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"QPushButton#parar_ejercicio{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#parar_ejercicio:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#parar_ejercicio:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"QPushButton#nuevo_punto{\n"
"background-color: rgb(0,0,0,0);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#nuevo_punto:hover {\n"
"    background-color: rgb(130, 235, 233,60);\n"
"}\n"
"QPushButton#nuevo_punto:pressed {\n"
"background-color: rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"QPushButton#guardar_ejercicio{\n"
"background-color: rgb(150, 255, 253);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#guardar_ejercicio:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QPushButton#guardar_ejercicio:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"QPushButton#reiniciar_seleccion{\n"
"background-color: rgb(110, 215, 213,0);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#reiniciar_seleccion:hover {\n"
"    background-color: rgb(130, 235, 233,60);\n"
"}\n"
"QPushButton#reiniciar_seleccion:pressed {\n"
"background-color: rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"QComboBox#seleccion_ejercicio{\n"
"background-color: rgb(140, 245, 243);\n"
"}\n"
"QComboBox#seleccion_ejercicio:hover {\n"
"    background-color: rgb(130, 235, 233);\n"
"}\n"
"QComboBox#seleccion_ejercicio:pressed {\n"
"    background-color: rgb(61, 181, 169);\n"
"}\n"
"\n"
"QPushButton#x_pos{\n"
"background-color: rgb(0,0,0,0);\n"
"    border-radius: 10px;}\n"
"QPushButton#x_pos:hover {\n"
"background-color: qradialgradient(spread:pad, cx:0.47, cy:0.506, radius:0.738, fx:0.47, fy:0.517, stop:0 rgba(255, 255, 255, 100), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"QPushButton#x_pos:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.670679, fx:0.5, fy:0.5, stop:0 rgba(149, 149, 149, 255), stop:0.746269 rgba(255, 255, 255, 0));\n"
"\n"
"}\n"
"QPushButton#x_neg{\n"
"background-color: rgb(0,0,0,0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#x_neg:hover {\n"
"background-color: qradialgradient(spread:pad, cx:0.47, cy:0.506, radius:0.738, fx:0.47, fy:0.517, stop:0 rgba(255, 255, 255, 100), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"QPushButton#x_neg:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.670679, fx:0.5, fy:0.5, stop:0 rgba(149, 149, 149, 255), stop:0.746269 rgba(255, 255, 255, 0));\n"
"\n"
"}\n"
"\n"
"QPushButton#y_pos{\n"
"background-color: rgb(0,0,0,0);\n"
"    border-radius: 10px;}\n"
"QPushButton#y_pos:hover {\n"
"background-color: qradialgradient(spread:pad, cx:0.47, cy:0.506, radius:0.738, fx:0.47, fy:0.517, stop:0 rgba(255, 255, 255, 100), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"QPushButton#y_pos:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.670679, fx:0.5, fy:0.5, stop:0 rgba(149, 149, 149, 255), stop:0.746269 rgba(255, 255, 255, 0));\n"
"}\n"
"QPushButton#y_neg{\n"
"background-color: rgb(0,0,0,0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#y_neg:hover {\n"
"background-color: qradialgradient(spread:pad, cx:0.47, cy:0.506, radius:0.738, fx:0.47, fy:0.517, stop:0 rgba(255, 255, 255, 100), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"QPushButton#y_neg:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.670679, fx:0.5, fy:0.5, stop:0 rgba(149, 149, 149, 255), stop:0.746269 rgba(255, 255, 255, 0));\n"
"}\n"
"QPushButton#z_pos{\n"
"background-color: rgb(0,0,0,0);\n"
"    border-radius: 10px;}\n"
"QPushButton#z_pos:hover {\n"
"background-color: qradialgradient(spread:pad, cx:0.47, cy:0.506, radius:0.738, fx:0.47, fy:0.517, stop:0 rgba(255, 255, 255, 100), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"QPushButton#z_pos:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.670679, fx:0.5, fy:0.5, stop:0 rgba(149, 149, 149, 255), stop:0.746269 rgba(255, 255, 255, 0));\n"
"}\n"
"QPushButton#z_neg{\n"
"background-color: rgb(0,0,0,0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#z_neg:hover {\n"
"background-color: qradialgradient(spread:pad, cx:0.47, cy:0.506, radius:0.738, fx:0.47, fy:0.517, stop:0 rgba(255, 255, 255, 100), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"QPushButton#z_neg:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.670679, fx:0.5, fy:0.5, stop:0 rgba(149, 149, 149, 255), stop:0.746269 rgba(255, 255, 255, 0));\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.value_q4 = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_q4.setGeometry(QtCore.QRect(180, 190, 69, 26))
        self.value_q4.setMinimum(-360.0)
        self.value_q4.setMaximum(360.0)
        self.value_q4.setSingleStep(0.1)
        self.value_q4.setObjectName("value_q4")
        self.q1_derecha = QtWidgets.QPushButton(self.tab)
        self.q1_derecha.setGeometry(QtCore.QRect(360, 70, 89, 25))
        self.q1_derecha.setStyleSheet("")
        self.q1_derecha.setObjectName("q1_derecha")
        self.value_q3 = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_q3.setGeometry(QtCore.QRect(180, 150, 69, 26))
        self.value_q3.setMinimum(-360.0)
        self.value_q3.setMaximum(360.0)
        self.value_q3.setSingleStep(0.1)
        self.value_q3.setObjectName("value_q3")
        self.q5_izquierda = QtWidgets.QPushButton(self.tab)
        self.q5_izquierda.setGeometry(QtCore.QRect(270, 230, 89, 25))
        self.q5_izquierda.setObjectName("q5_izquierda")
        self.q4_derecha = QtWidgets.QPushButton(self.tab)
        self.q4_derecha.setGeometry(QtCore.QRect(360, 190, 89, 25))
        self.q4_derecha.setObjectName("q4_derecha")
        self.q3_izquierda = QtWidgets.QPushButton(self.tab)
        self.q3_izquierda.setGeometry(QtCore.QRect(270, 150, 89, 25))
        self.q3_izquierda.setObjectName("q3_izquierda")
        self.q4_izquierda = QtWidgets.QPushButton(self.tab)
        self.q4_izquierda.setGeometry(QtCore.QRect(270, 190, 89, 25))
        self.q4_izquierda.setObjectName("q4_izquierda")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 53, 161, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.slider_q1 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_q1.setEnabled(True)
        self.slider_q1.setMinimum(-3600)
        self.slider_q1.setMaximum(3600)
        self.slider_q1.setSingleStep(1)
        self.slider_q1.setPageStep(0)
        self.slider_q1.setProperty("value", 0)
        self.slider_q1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_q1.setObjectName("slider_q1")
        self.verticalLayout.addWidget(self.slider_q1)
        self.slider_q2 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_q2.setMinimum(-3600)
        self.slider_q2.setMaximum(3600)
        self.slider_q2.setPageStep(1)
        self.slider_q2.setProperty("value", -900)
        self.slider_q2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_q2.setObjectName("slider_q2")
        self.verticalLayout.addWidget(self.slider_q2)
        self.slider_q3 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_q3.setMinimum(-3600)
        self.slider_q3.setMaximum(3600)
        self.slider_q3.setPageStep(1)
        self.slider_q3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_q3.setObjectName("slider_q3")
        self.verticalLayout.addWidget(self.slider_q3)
        self.slider_q4 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_q4.setMinimum(-3600)
        self.slider_q4.setMaximum(3600)
        self.slider_q4.setPageStep(1)
        self.slider_q4.setProperty("value", -900)
        self.slider_q4.setSliderPosition(-900)
        self.slider_q4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_q4.setObjectName("slider_q4")
        self.verticalLayout.addWidget(self.slider_q4)
        self.slider_q5 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_q5.setMinimum(-3600)
        self.slider_q5.setMaximum(3600)
        self.slider_q5.setOrientation(QtCore.Qt.Horizontal)
        self.slider_q5.setObjectName("slider_q5")
        self.verticalLayout.addWidget(self.slider_q5)
        self.slider_q6 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_q6.setMinimum(-3600)
        self.slider_q6.setMaximum(3600)
        self.slider_q6.setPageStep(1)
        self.slider_q6.setOrientation(QtCore.Qt.Horizontal)
        self.slider_q6.setObjectName("slider_q6")
        self.verticalLayout.addWidget(self.slider_q6)
        self.q1_izquierda = QtWidgets.QPushButton(self.tab)
        self.q1_izquierda.setGeometry(QtCore.QRect(270, 70, 89, 25))
        self.q1_izquierda.setObjectName("q1_izquierda")
        self.q2_izquierda = QtWidgets.QPushButton(self.tab)
        self.q2_izquierda.setGeometry(QtCore.QRect(270, 110, 89, 25))
        self.q2_izquierda.setObjectName("q2_izquierda")
        self.q5_derecha = QtWidgets.QPushButton(self.tab)
        self.q5_derecha.setGeometry(QtCore.QRect(360, 230, 89, 25))
        self.q5_derecha.setObjectName("q5_derecha")
        self.value_q6 = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_q6.setGeometry(QtCore.QRect(180, 270, 69, 26))
        self.value_q6.setMinimum(-360.0)
        self.value_q6.setMaximum(360.0)
        self.value_q6.setSingleStep(0.1)
        self.value_q6.setObjectName("value_q6")
        self.value_q2 = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_q2.setGeometry(QtCore.QRect(180, 110, 69, 26))
        self.value_q2.setMinimum(-360.0)
        self.value_q2.setMaximum(360.0)
        self.value_q2.setSingleStep(0.1)
        self.value_q2.setObjectName("value_q2")
        self.value_q1 = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_q1.setGeometry(QtCore.QRect(180, 70, 69, 26))
        self.value_q1.setMinimum(-360.0)
        self.value_q1.setMaximum(360.0)
        self.value_q1.setSingleStep(0.1)
        self.value_q1.setObjectName("value_q1")
        self.q6_izquierda = QtWidgets.QPushButton(self.tab)
        self.q6_izquierda.setGeometry(QtCore.QRect(270, 270, 89, 25))
        self.q6_izquierda.setObjectName("q6_izquierda")
        self.q3_derecha = QtWidgets.QPushButton(self.tab)
        self.q3_derecha.setGeometry(QtCore.QRect(360, 150, 89, 25))
        self.q3_derecha.setObjectName("q3_derecha")
        self.value_q5 = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_q5.setGeometry(QtCore.QRect(180, 230, 69, 26))
        self.value_q5.setMinimum(-360.0)
        self.value_q5.setMaximum(360.0)
        self.value_q5.setSingleStep(0.1)
        self.value_q5.setObjectName("value_q5")
        self.q2_derecha = QtWidgets.QPushButton(self.tab)
        self.q2_derecha.setGeometry(QtCore.QRect(360, 110, 89, 25))
        self.q2_derecha.setObjectName("q2_derecha")
        self.q6_derecha = QtWidgets.QPushButton(self.tab)
        self.q6_derecha.setGeometry(QtCore.QRect(360, 270, 89, 25))
        self.q6_derecha.setStyleSheet("")
        self.q6_derecha.setObjectName("q6_derecha")
        self.seleccion_ejercicio = QtWidgets.QComboBox(self.tab)
        self.seleccion_ejercicio.setGeometry(QtCore.QRect(90, 387, 111, 31))
        self.seleccion_ejercicio.setObjectName("seleccion_ejercicio")
        self.home = QtWidgets.QPushButton(self.tab)
        self.home.setGeometry(QtCore.QRect(480, 70, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.home.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home.setFont(font)
        self.home.setObjectName("home")
        self.nuevo_punto = QtWidgets.QPushButton(self.tab)
        self.nuevo_punto.setGeometry(QtCore.QRect(410, 427, 31, 31))
        self.nuevo_punto.setText("")
        self.nuevo_punto.setObjectName("nuevo_punto")
        self.reiniciar_seleccion = QtWidgets.QPushButton(self.tab)
        self.reiniciar_seleccion.setGeometry(QtCore.QRect(450, 427, 31, 31))
        self.reiniciar_seleccion.setText("")
        self.reiniciar_seleccion.setObjectName("reiniciar_seleccion")
        self.guardar_ejercicio = QtWidgets.QPushButton(self.tab)
        self.guardar_ejercicio.setGeometry(QtCore.QRect(490, 427, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.guardar_ejercicio.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.guardar_ejercicio.setFont(font)
        self.guardar_ejercicio.setObjectName("guardar_ejercicio")
        self.parar_ejercicio = QtWidgets.QPushButton(self.tab)
        self.parar_ejercicio.setGeometry(QtCore.QRect(410, 387, 89, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.parar_ejercicio.setPalette(palette)
        self.parar_ejercicio.setObjectName("parar_ejercicio")
        self.visualizar_ejercicio = QtWidgets.QPushButton(self.tab)
        self.visualizar_ejercicio.setGeometry(QtCore.QRect(210, 387, 89, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.visualizar_ejercicio.setPalette(palette)
        self.visualizar_ejercicio.setObjectName("visualizar_ejercicio")
        self.radio_nuevo_ejercicio = QtWidgets.QDoubleSpinBox(self.tab)
        self.radio_nuevo_ejercicio.setGeometry(QtCore.QRect(310, 463, 69, 26))
        self.radio_nuevo_ejercicio.setObjectName("radio_nuevo_ejercicio")
        self.angulo_nuevo_ejercicio = QtWidgets.QDoubleSpinBox(self.tab)
        self.angulo_nuevo_ejercicio.setGeometry(QtCore.QRect(120, 462, 69, 26))
        self.angulo_nuevo_ejercicio.setObjectName("angulo_nuevo_ejercicio")
        self.puntos_seleccionados = QtWidgets.QTextBrowser(self.tab)
        self.puntos_seleccionados.setGeometry(QtCore.QRect(40, 498, 731, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.puntos_seleccionados.setPalette(palette)
        self.puntos_seleccionados.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"font-color:rgb(255,255,255);")
        self.puntos_seleccionados.setObjectName("puntos_seleccionados")
        self.boton_ej_lineal = QtWidgets.QRadioButton(self.tab)
        self.boton_ej_lineal.setGeometry(QtCore.QRect(520, 387, 141, 23))
        palette = QtGui.QPalette()
        self.boton_ej_lineal.setPalette(palette)
        self.boton_ej_lineal.setObjectName("boton_ej_lineal")
        self.boton_ej_circular = QtWidgets.QRadioButton(self.tab)
        self.boton_ej_circular.setGeometry(QtCore.QRect(650, 387, 141, 23))
        palette = QtGui.QPalette()
        self.boton_ej_circular.setPalette(palette)
        self.boton_ej_circular.setObjectName("boton_ej_circular")
        self.y_pos = QtWidgets.QPushButton(self.tab)
        self.y_pos.setGeometry(QtCore.QRect(583, 210, 51, 71))
        self.y_pos.setText("")
        self.y_pos.setObjectName("y_pos")
        self.y_neg = QtWidgets.QPushButton(self.tab)
        self.y_neg.setGeometry(QtCore.QRect(595, 155, 31, 33))
        self.y_neg.setText("")
        self.y_neg.setObjectName("y_neg")
        self.x_pos = QtWidgets.QPushButton(self.tab)
        self.x_pos.setGeometry(QtCore.QRect(620, 180, 81, 41))
        self.x_pos.setText("")
        self.x_pos.setObjectName("x_pos")
        self.x_neg = QtWidgets.QPushButton(self.tab)
        self.x_neg.setGeometry(QtCore.QRect(512, 180, 91, 41))
        self.x_neg.setText("")
        self.x_neg.setObjectName("x_neg")
        self.z_pos = QtWidgets.QPushButton(self.tab)
        self.z_pos.setGeometry(QtCore.QRect(712, 138, 41, 61))
        self.z_pos.setText("")
        self.z_pos.setObjectName("z_pos")
        self.z_neg = QtWidgets.QPushButton(self.tab)
        self.z_neg.setGeometry(QtCore.QRect(712, 210, 41, 71))
        self.z_neg.setText("")
        self.z_neg.setObjectName("z_neg")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(410, 427, 31, 31))
        self.label_2.setStyleSheet("background-color: rgb(150, 255, 253);\n"
"image: url(:/prefijoNuevo/1655993721814.png);\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-width:1000px;\n"
"    border-radius:10px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(450, 427, 31, 31))
        self.label_3.setStyleSheet("image: url(:/prefijoNuevo/477200.png);\n"
"background-color: rgb(150, 255, 253);\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius:10px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.repeticiones = QtWidgets.QDoubleSpinBox(self.tab)
        self.repeticiones.setGeometry(QtCore.QRect(310, 427, 69, 26))
        self.repeticiones.setObjectName("repeticiones")
        self.duracion = QtWidgets.QDoubleSpinBox(self.tab)
        self.duracion.setGeometry(QtCore.QRect(120, 427, 69, 26))
        self.duracion.setObjectName("duracion")
        self.ejecutar_ejercicio = QtWidgets.QPushButton(self.tab)
        self.ejecutar_ejercicio.setGeometry(QtCore.QRect(310, 387, 89, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ejecutar_ejercicio.setPalette(palette)
        self.ejecutar_ejercicio.setObjectName("ejecutar_ejercicio")
        self.value_x = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_x.setGeometry(QtCore.QRect(610, 60, 39, 21))
        self.value_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.value_x.setMinimum(-360.0)
        self.value_x.setMaximum(360.0)
        self.value_x.setSingleStep(0.1)
        self.value_x.setObjectName("value_x")
        self.value_y = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_y.setGeometry(QtCore.QRect(610, 80, 39, 21))
        self.value_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.value_y.setMinimum(-360.0)
        self.value_y.setMaximum(360.0)
        self.value_y.setSingleStep(0.1)
        self.value_y.setObjectName("value_y")
        self.value_z = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_z.setGeometry(QtCore.QRect(610, 100, 39, 21))
        self.value_z.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.value_z.setMinimum(-360.0)
        self.value_z.setMaximum(360.0)
        self.value_z.setSingleStep(0.1)
        self.value_z.setObjectName("value_z")
        self.value_rx = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_rx.setGeometry(QtCore.QRect(720, 60, 39, 21))
        self.value_rx.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.value_rx.setMinimum(-360.0)
        self.value_rx.setMaximum(360.0)
        self.value_rx.setSingleStep(0.1)
        self.value_rx.setObjectName("value_rx")
        self.value_rz = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_rz.setGeometry(QtCore.QRect(720, 100, 39, 21))
        self.value_rz.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.value_rz.setMinimum(-360.0)
        self.value_rz.setMaximum(360.0)
        self.value_rz.setSingleStep(0.1)
        self.value_rz.setObjectName("value_rz")
        self.value_ry = QtWidgets.QDoubleSpinBox(self.tab)
        self.value_ry.setGeometry(QtCore.QRect(720, 80, 39, 21))
        self.value_ry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.value_ry.setMinimum(-360.0)
        self.value_ry.setMaximum(360.0)
        self.value_ry.setSingleStep(0.1)
        self.value_ry.setObjectName("value_ry")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(590, 62, 21, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(590, 82, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(590, 102, 21, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(690, 102, 31, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(690, 82, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(690, 62, 31, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(650, 102, 31, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(650, 82, 31, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(650, 62, 31, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(760, 100, 31, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(760, 60, 31, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(760, 80, 31, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 432, 111, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(200, 432, 111, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(20, 390, 111, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(215, 467, 111, 17))
        self.label_19.setObjectName("label_19")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(41, 467, 111, 17))
        self.label_26.setObjectName("label_26")
        self.verticalFrame = QtWidgets.QFrame(self.tab)
        self.verticalFrame.setGeometry(QtCore.QRect(-20, 320, 841, 6))
        self.verticalFrame.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, -2, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalFrame_6 = QtWidgets.QFrame(self.tab)
        self.verticalFrame_6.setGeometry(QtCore.QRect(-30, 0, 846, 6))
        self.verticalFrame_6.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.verticalFrame_6.setObjectName("verticalFrame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalFrame_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalFrame_7 = QtWidgets.QFrame(self.tab)
        self.verticalFrame_7.setGeometry(QtCore.QRect(-10, 40, 841, 5))
        self.verticalFrame_7.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.verticalFrame_7.setObjectName("verticalFrame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalFrame_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(10, 317, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalFrame_8 = QtWidgets.QFrame(self.tab)
        self.verticalFrame_8.setGeometry(QtCore.QRect(-10, 360, 841, 5))
        self.verticalFrame_8.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.verticalFrame_8.setObjectName("verticalFrame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalFrame_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(520, 110, 239, 199))
        self.label_28.setStyleSheet("image: url(:/prefijoNuevo/1656236018993.png);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(490, 210, 67, 17))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(85, 87, 83);")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(560, 270, 67, 17))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(85, 87, 83);")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(680, 130, 67, 31))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(85, 87, 83);")
        self.label_31.setObjectName("label_31")
        self.label_28.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.value_q4.raise_()
        self.q1_derecha.raise_()
        self.value_q3.raise_()
        self.q5_izquierda.raise_()
        self.q4_derecha.raise_()
        self.q3_izquierda.raise_()
        self.q4_izquierda.raise_()
        self.layoutWidget.raise_()
        self.q1_izquierda.raise_()
        self.q2_izquierda.raise_()
        self.q5_derecha.raise_()
        self.value_q6.raise_()
        self.value_q2.raise_()
        self.value_q1.raise_()
        self.q6_izquierda.raise_()
        self.q3_derecha.raise_()
        self.value_q5.raise_()
        self.q2_derecha.raise_()
        self.q6_derecha.raise_()
        self.seleccion_ejercicio.raise_()
        self.home.raise_()
        self.guardar_ejercicio.raise_()
        self.parar_ejercicio.raise_()
        self.visualizar_ejercicio.raise_()
        self.radio_nuevo_ejercicio.raise_()
        self.angulo_nuevo_ejercicio.raise_()
        self.puntos_seleccionados.raise_()
        self.boton_ej_lineal.raise_()
        self.boton_ej_circular.raise_()
        self.y_neg.raise_()
        self.x_pos.raise_()
        self.z_pos.raise_()
        self.z_neg.raise_()
        self.reiniciar_seleccion.raise_()
        self.nuevo_punto.raise_()
        self.repeticiones.raise_()
        self.duracion.raise_()
        self.ejecutar_ejercicio.raise_()
        self.value_x.raise_()
        self.value_y.raise_()
        self.value_z.raise_()
        self.value_rx.raise_()
        self.value_rz.raise_()
        self.value_ry.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_26.raise_()
        self.verticalFrame.raise_()
        self.label.raise_()
        self.verticalFrame_6.raise_()
        self.verticalFrame_7.raise_()
        self.label_23.raise_()
        self.verticalFrame_8.raise_()
        self.y_pos.raise_()
        self.x_neg.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        palette = QtGui.QPalette()
        gradient = QtGui.QRadialGradient(0.295522, 0.590909, 2.0, 0.445716, 0.392409)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.955224, QtGui.QColor(158, 158, 158))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QRadialGradient(0.295522, 0.590909, 2.0, 0.445716, 0.392409)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.955224, QtGui.QColor(158, 158, 158))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.295522, 0.590909, 2.0, 0.445716, 0.392409)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.955224, QtGui.QColor(158, 158, 158))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QRadialGradient(0.295522, 0.590909, 2.0, 0.445716, 0.392409)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.955224, QtGui.QColor(158, 158, 158))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QRadialGradient(0.295522, 0.590909, 2.0, 0.445716, 0.392409)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.955224, QtGui.QColor(158, 158, 158))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.295522, 0.590909, 2.0, 0.445716, 0.392409)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.955224, QtGui.QColor(158, 158, 158))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QRadialGradient(0.295522, 0.590909, 2.0, 0.445716, 0.392409)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.955224, QtGui.QColor(158, 158, 158))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QRadialGradient(0.295522, 0.590909, 2.0, 0.445716, 0.392409)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.955224, QtGui.QColor(158, 158, 158))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.295522, 0.590909, 2.0, 0.445716, 0.392409)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.955224, QtGui.QColor(158, 158, 158))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tab_2.setPalette(palette)
        self.tab_2.setObjectName("tab_2")
        self.plot_fz = QwtPlot(self.tab_2)
        self.plot_fz.setGeometry(QtCore.QRect(20, 485, 361, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plot_fz.setPalette(palette)
        self.plot_fz.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"border:0px")
        self.plot_fz.setObjectName("plot_fz")
        self.plot_vx = QwtPlot(self.tab_2)
        self.plot_vx.setGeometry(QtCore.QRect(410, 70, 361, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plot_vx.setPalette(palette)
        self.plot_vx.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"border:0px")
        self.plot_vx.setObjectName("plot_vx")
        self.plot_fy = QwtPlot(self.tab_2)
        self.plot_fy.setGeometry(QtCore.QRect(20, 277, 361, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plot_fy.setPalette(palette)
        self.plot_fy.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"border:0px")
        self.plot_fy.setObjectName("plot_fy")
        self.plot_fx = QwtPlot(self.tab_2)
        self.plot_fx.setGeometry(QtCore.QRect(20, 70, 361, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plot_fx.setPalette(palette)
        self.plot_fx.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"border:0px")
        self.plot_fx.setObjectName("plot_fx")
        self.guardar_mediciones = QtWidgets.QPushButton(self.tab_2)
        self.guardar_mediciones.setGeometry(QtCore.QRect(630, 10, 141, 25))
        self.guardar_mediciones.setObjectName("guardar_mediciones")
        self.plot_vy = QwtPlot(self.tab_2)
        self.plot_vy.setGeometry(QtCore.QRect(410, 277, 361, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plot_vy.setPalette(palette)
        self.plot_vy.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"border:0px")
        self.plot_vy.setObjectName("plot_vy")
        self.play_stop = QtWidgets.QPushButton(self.tab_2)
        self.play_stop.setGeometry(QtCore.QRect(70, 10, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(110, 215, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 215, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 215, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.play_stop.setPalette(palette)
        self.play_stop.setObjectName("play_stop")
        self.plot_vz = QwtPlot(self.tab_2)
        self.plot_vz.setGeometry(QtCore.QRect(410, 485, 361, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 64, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plot_vz.setPalette(palette)
        self.plot_vz.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"border:0px")
        self.plot_vz.setObjectName("plot_vz")
        self.configuracion = QtWidgets.QToolButton(self.tab_2)
        self.configuracion.setGeometry(QtCore.QRect(170, 10, 26, 24))
        self.configuracion.setObjectName("configuracion")
        self.eje_x = QtWidgets.QRadioButton(self.tab_2)
        self.eje_x.setGeometry(QtCore.QRect(590, 40, 112, 23))
        self.eje_x.setAutoExclusive(False)
        self.eje_x.setObjectName("eje_x")
        self.eje_y = QtWidgets.QRadioButton(self.tab_2)
        self.eje_y.setGeometry(QtCore.QRect(650, 40, 112, 23))
        self.eje_y.setAutoExclusive(False)
        self.eje_y.setObjectName("eje_y")
        self.eje_z = QtWidgets.QRadioButton(self.tab_2)
        self.eje_z.setGeometry(QtCore.QRect(710, 40, 112, 23))
        self.eje_z.setAutoExclusive(False)
        self.eje_z.setObjectName("eje_z")
        self.plot_x_mas = QtWidgets.QPushButton(self.tab_2)
        self.plot_x_mas.setGeometry(QtCore.QRect(190, 50, 41, 20))
        self.plot_x_mas.setObjectName("plot_x_mas")
        self.plot_x_menos = QtWidgets.QPushButton(self.tab_2)
        self.plot_x_menos.setGeometry(QtCore.QRect(150, 50, 41, 20))
        self.plot_x_menos.setObjectName("plot_x_menos")
        self.plot_y_menos = QtWidgets.QPushButton(self.tab_2)
        self.plot_y_menos.setGeometry(QtCore.QRect(150, 257, 41, 20))
        self.plot_y_menos.setObjectName("plot_y_menos")
        self.plot_y_mas = QtWidgets.QPushButton(self.tab_2)
        self.plot_y_mas.setGeometry(QtCore.QRect(190, 257, 41, 20))
        self.plot_y_mas.setObjectName("plot_y_mas")
        self.plot_z_menos = QtWidgets.QPushButton(self.tab_2)
        self.plot_z_menos.setGeometry(QtCore.QRect(150, 465, 41, 20))
        self.plot_z_menos.setObjectName("plot_z_menos")
        self.plot_z_mas = QtWidgets.QPushButton(self.tab_2)
        self.plot_z_mas.setGeometry(QtCore.QRect(190, 465, 41, 20))
        self.plot_z_mas.setObjectName("plot_z_mas")
        self.plotx_reducir = QtWidgets.QPushButton(self.tab_2)
        self.plotx_reducir.setGeometry(QtCore.QRect(70, 50, 41, 20))
        self.plotx_reducir.setText("")
        self.plotx_reducir.setObjectName("plotx_reducir")
        self.plotx_ampliar = QtWidgets.QPushButton(self.tab_2)
        self.plotx_ampliar.setGeometry(QtCore.QRect(110, 50, 41, 20))
        self.plotx_ampliar.setText("")
        self.plotx_ampliar.setObjectName("plotx_ampliar")
        self.ploty_ampliar = QtWidgets.QPushButton(self.tab_2)
        self.ploty_ampliar.setGeometry(QtCore.QRect(110, 257, 41, 20))
        self.ploty_ampliar.setText("")
        self.ploty_ampliar.setObjectName("ploty_ampliar")
        self.ploty_reducir = QtWidgets.QPushButton(self.tab_2)
        self.ploty_reducir.setGeometry(QtCore.QRect(70, 257, 41, 20))
        self.ploty_reducir.setText("")
        self.ploty_reducir.setObjectName("ploty_reducir")
        self.plotz_ampliar = QtWidgets.QPushButton(self.tab_2)
        self.plotz_ampliar.setGeometry(QtCore.QRect(110, 465, 41, 20))
        self.plotz_ampliar.setText("")
        self.plotz_ampliar.setObjectName("plotz_ampliar")
        self.plotz_reducir = QtWidgets.QPushButton(self.tab_2)
        self.plotz_reducir.setGeometry(QtCore.QRect(70, 465, 41, 20))
        self.plotz_reducir.setText("")
        self.plotz_reducir.setObjectName("plotz_reducir")
        self.actualizar_x = QtWidgets.QPushButton(self.tab_2)
        self.actualizar_x.setGeometry(QtCore.QRect(230, 50, 31, 20))
        self.actualizar_x.setText("")
        self.actualizar_x.setObjectName("actualizar_x")
        self.actualizar_y = QtWidgets.QPushButton(self.tab_2)
        self.actualizar_y.setGeometry(QtCore.QRect(230, 257, 31, 20))
        self.actualizar_y.setText("")
        self.actualizar_y.setObjectName("actualizar_y")
        self.actualizar_z = QtWidgets.QPushButton(self.tab_2)
        self.actualizar_z.setGeometry(QtCore.QRect(230, 465, 31, 20))
        self.actualizar_z.setText("")
        self.actualizar_z.setObjectName("actualizar_z")
        self.cargar_mediciones = QtWidgets.QPushButton(self.tab_2)
        self.cargar_mediciones.setGeometry(QtCore.QRect(480, 10, 141, 25))
        self.cargar_mediciones.setObjectName("cargar_mediciones")
        self.conectar_robot_fuerza = QtWidgets.QRadioButton(self.tab_2)
        self.conectar_robot_fuerza.setGeometry(QtCore.QRect(400, -30, 112, 23))
        self.conectar_robot_fuerza.setObjectName("conectar_robot_fuerza")
        self.fuerza_primera_x = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.fuerza_primera_x.setGeometry(QtCore.QRect(310, 50, 69, 20))
        self.fuerza_primera_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fuerza_primera_x.setKeyboardTracking(True)
        self.fuerza_primera_x.setPrefix("")
        self.fuerza_primera_x.setSuffix("")
        self.fuerza_primera_x.setDecimals(5)
        self.fuerza_primera_x.setMinimum(-300.0)
        self.fuerza_primera_x.setMaximum(300.0)
        self.fuerza_primera_x.setObjectName("fuerza_primera_x")
        self.fuerza_primera_y = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.fuerza_primera_y.setGeometry(QtCore.QRect(310, 257, 69, 20))
        self.fuerza_primera_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fuerza_primera_y.setKeyboardTracking(True)
        self.fuerza_primera_y.setDecimals(5)
        self.fuerza_primera_y.setMinimum(-300.0)
        self.fuerza_primera_y.setMaximum(300.0)
        self.fuerza_primera_y.setObjectName("fuerza_primera_y")
        self.fuerza_primera_z = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.fuerza_primera_z.setGeometry(QtCore.QRect(310, 465, 69, 20))
        self.fuerza_primera_z.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fuerza_primera_z.setKeyboardTracking(True)
        self.fuerza_primera_z.setDecimals(5)
        self.fuerza_primera_z.setMinimum(-300.0)
        self.fuerza_primera_z.setMaximum(300.0)
        self.fuerza_primera_z.setObjectName("fuerza_primera_z")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(180, 230, 71, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(580, 230, 71, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(180, 635, 71, 17))
        self.label_22.setObjectName("label_22")
        self.verticalFrame1 = QtWidgets.QFrame(self.tab_2)
        self.verticalFrame1.setGeometry(QtCore.QRect(4, 470, 16, 121))
        self.verticalFrame1.setStyleSheet("image: url(:/prefijoNuevo/1656163481247.png);")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalFrame_2 = QtWidgets.QFrame(self.tab_2)
        self.verticalFrame_2.setGeometry(QtCore.QRect(4, 270, 17, 121))
        self.verticalFrame_2.setStyleSheet("image: url(:/prefijoNuevo/1656163481118.png);")
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalFrame_3 = QtWidgets.QFrame(self.tab_2)
        self.verticalFrame_3.setGeometry(QtCore.QRect(4, 60, 16, 121))
        self.verticalFrame_3.setStyleSheet("image: url(:/prefijoNuevo/1656163480958.png);")
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalFrame_4 = QtWidgets.QFrame(self.tab_2)
        self.verticalFrame_4.setGeometry(QtCore.QRect(380, 53, 41, 151))
        self.verticalFrame_4.setStyleSheet("image: url(:/prefijoNuevo/1656163480524.png);")
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalFrame_5 = QtWidgets.QFrame(self.tab_2)
        self.verticalFrame_5.setGeometry(QtCore.QRect(383, 269, 31, 141))
        self.verticalFrame_5.setStyleSheet("image: url(:/prefijoNuevo/1656163480689.png);")
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.nombre_ejercicio = QtWidgets.QLabel(self.tab_2)
        self.nombre_ejercicio.setGeometry(QtCore.QRect(360, 13, 111, 21))
        self.nombre_ejercicio.setText("")
        self.nombre_ejercicio.setObjectName("nombre_ejercicio")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(580, 440, 71, 17))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(580, 635, 71, 17))
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(180, 440, 71, 17))
        self.label_27.setObjectName("label_27")
        self.verticalFrame_9 = QtWidgets.QFrame(self.tab_2)
        self.verticalFrame_9.setGeometry(QtCore.QRect(384, 470, 31, 141))
        self.verticalFrame_9.setStyleSheet("image: url(:/prefijoNuevo/1656163480829.png);")
        self.verticalFrame_9.setObjectName("verticalFrame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.fuerza_primera_z.raise_()
        self.fuerza_primera_y.raise_()
        self.fuerza_primera_x.raise_()
        self.actualizar_z.raise_()
        self.actualizar_y.raise_()
        self.actualizar_x.raise_()
        self.plot_fz.raise_()
        self.plot_vx.raise_()
        self.plot_fy.raise_()
        self.plot_fx.raise_()
        self.guardar_mediciones.raise_()
        self.plot_vy.raise_()
        self.play_stop.raise_()
        self.plot_vz.raise_()
        self.configuracion.raise_()
        self.eje_x.raise_()
        self.eje_y.raise_()
        self.eje_z.raise_()
        self.plot_x_mas.raise_()
        self.plot_x_menos.raise_()
        self.plot_y_menos.raise_()
        self.plot_y_mas.raise_()
        self.plot_z_menos.raise_()
        self.plot_z_mas.raise_()
        self.plotx_reducir.raise_()
        self.plotx_ampliar.raise_()
        self.ploty_ampliar.raise_()
        self.ploty_reducir.raise_()
        self.plotz_ampliar.raise_()
        self.plotz_reducir.raise_()
        self.cargar_mediciones.raise_()
        self.conectar_robot_fuerza.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.verticalFrame.raise_()
        self.verticalFrame_2.raise_()
        self.verticalFrame_3.raise_()
        self.verticalFrame_4.raise_()
        self.verticalFrame_5.raise_()
        self.nombre_ejercicio.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_27.raise_()
        self.verticalFrame_9.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.conectar_robot = QtWidgets.QRadioButton(self.centralwidget)
        self.conectar_robot.setGeometry(QtCore.QRect(660, 2, 131, 23))
        self.conectar_robot.setObjectName("conectar_robot")
        MainWindow_control.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_control)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 22))
        self.menubar.setObjectName("menubar")
        MainWindow_control.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_control)
        self.statusbar.setObjectName("statusbar")
        MainWindow_control.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_control)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_control)

    def retranslateUi(self, MainWindow_control):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_control.setWindowTitle(_translate("MainWindow_control", "Control"))
        self.q1_derecha.setText(_translate("MainWindow_control", "-->"))
        self.q5_izquierda.setText(_translate("MainWindow_control", "<--"))
        self.q4_derecha.setText(_translate("MainWindow_control", "-->"))
        self.q3_izquierda.setText(_translate("MainWindow_control", "<--"))
        self.q4_izquierda.setText(_translate("MainWindow_control", "<--"))
        self.q1_izquierda.setText(_translate("MainWindow_control", "<--"))
        self.q2_izquierda.setText(_translate("MainWindow_control", "<--"))
        self.q5_derecha.setText(_translate("MainWindow_control", "-->"))
        self.q6_izquierda.setText(_translate("MainWindow_control", "<--"))
        self.q3_derecha.setText(_translate("MainWindow_control", "-->"))
        self.q2_derecha.setText(_translate("MainWindow_control", "-->"))
        self.q6_derecha.setText(_translate("MainWindow_control", "-->"))
        self.home.setText(_translate("MainWindow_control", "Home"))
        self.guardar_ejercicio.setText(_translate("MainWindow_control", "guardar ejercicio"))
        self.parar_ejercicio.setText(_translate("MainWindow_control", "Parar"))
        self.visualizar_ejercicio.setText(_translate("MainWindow_control", "Visualizar"))
        self.puntos_seleccionados.setHtml(_translate("MainWindow_control", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.boton_ej_lineal.setText(_translate("MainWindow_control", "Ejercicio lineal"))
        self.boton_ej_circular.setText(_translate("MainWindow_control", "Ejercicio circular"))
        self.ejecutar_ejercicio.setText(_translate("MainWindow_control", "Ejecutar"))
        self.label_4.setText(_translate("MainWindow_control", "X:"))
        self.label_5.setText(_translate("MainWindow_control", "Y:"))
        self.label_6.setText(_translate("MainWindow_control", "Z:"))
        self.label_7.setText(_translate("MainWindow_control", "RZ:"))
        self.label_8.setText(_translate("MainWindow_control", "RY:"))
        self.label_9.setText(_translate("MainWindow_control", "RX:"))
        self.label_10.setText(_translate("MainWindow_control", "mm"))
        self.label_11.setText(_translate("MainWindow_control", "mm"))
        self.label_12.setText(_translate("MainWindow_control", "mm"))
        self.label_13.setText(_translate("MainWindow_control", "º"))
        self.label_14.setText(_translate("MainWindow_control", "º"))
        self.label_15.setText(_translate("MainWindow_control", "º"))
        self.label_16.setText(_translate("MainWindow_control", "Dueración(s):"))
        self.label_17.setText(_translate("MainWindow_control", "Repeticiones:"))
        self.label_18.setText(_translate("MainWindow_control", "Ejercicio:"))
        self.label_19.setText(_translate("MainWindow_control", "Radio(mm):"))
        self.label_26.setText(_translate("MainWindow_control", "Ángulo(º):"))
        self.label.setText(_translate("MainWindow_control", "MOVIMIENTO MANUAL"))
        self.label_23.setText(_translate("MainWindow_control", "EJERCICIOS"))
        self.label_29.setText(_translate("MainWindow_control", "X"))
        self.label_30.setText(_translate("MainWindow_control", "Y"))
        self.label_31.setText(_translate("MainWindow_control", "Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow_control", "Control de posición"))
        self.guardar_mediciones.setText(_translate("MainWindow_control", "Guardar mediciones"))
        self.play_stop.setText(_translate("MainWindow_control", "Iniciar"))
        self.configuracion.setText(_translate("MainWindow_control", "..."))
        self.eje_x.setText(_translate("MainWindow_control", "Eje x"))
        self.eje_y.setText(_translate("MainWindow_control", "Eje y"))
        self.eje_z.setText(_translate("MainWindow_control", "Eje z"))
        self.plot_x_mas.setText(_translate("MainWindow_control", "->"))
        self.plot_x_menos.setText(_translate("MainWindow_control", "<-"))
        self.plot_y_menos.setText(_translate("MainWindow_control", "<-"))
        self.plot_y_mas.setText(_translate("MainWindow_control", "->"))
        self.plot_z_menos.setText(_translate("MainWindow_control", "<-"))
        self.plot_z_mas.setText(_translate("MainWindow_control", "->"))
        self.cargar_mediciones.setText(_translate("MainWindow_control", "Cargar mediciones"))
        self.conectar_robot_fuerza.setText(_translate("MainWindow_control", "RadioButton"))
        self.label_20.setText(_translate("MainWindow_control", "Tiempo(s)"))
        self.label_21.setText(_translate("MainWindow_control", "Tiempo(s)"))
        self.label_22.setText(_translate("MainWindow_control", "Tiempo(s)"))
        self.nombre_ejercicio.setToolTip(_translate("MainWindow_control", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.label_24.setText(_translate("MainWindow_control", "Tiempo(s)"))
        self.label_25.setText(_translate("MainWindow_control", "Tiempo(s)"))
        self.label_27.setText(_translate("MainWindow_control", "Tiempo(s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_control", "Control de fuerza"))
        self.conectar_robot.setText(_translate("MainWindow_control", "Conectar robot"))
from qwt import QwtPlot
from images import resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_control = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_control()
    ui.setupUi(MainWindow_control)
    MainWindow_control.show()
    sys.exit(app.exec_())
